feat: add tasks to upload necessary supporting data for prez and sparql update expansion queries

diff --git a/azure-pipelines/deploy-env/dev.yml b/azure-pipelines/deploy-env/dev.yml
--- a/azure-pipelines/deploy-env/dev.yml
+++ b/azure-pipelines/deploy-env/dev.yml
@@ -101,6 +101,38 @@ jobs:
                   curl -k -u '$(FUSEKI_USERNAME):$(FUSEKI_PASSWORD)' -H "Host: $(FUSEKI_DOMAIN_NAME)" https://localhost:8443/$/ping
 
             - task: CmdLine@2
+              displayName: "Upload background resources"
+              inputs:
+                script: |
+                  kurra file upload background-resources/ 'https://localhost:8443/$(FUSEKI_DATASET)' --username '$(FUSEKI_USERNAME)' --password '$(FUSEKI_PASSWORD)' --insecure
+
+            - task: CmdLine@2
+              displayName: "Upload prez catalogue"
+              inputs:
+                script: |
+                  kurra file upload prez/ 'https://localhost:8443/$(FUSEKI_DATASET)' --username '$(FUSEKI_USERNAME)' --password '$(FUSEKI_PASSWORD)' --insecure
+
+            - task: CmdLine@2
+              displayName: "Apply Prez SPARQL Update data expansion queries"
+              inputs:
+                script: |
+                  # Run all SPARQL update queries in the prez-queries folder
+                  for query_file in prez-queries/*.ru; do
+                    echo "Applying query: $query_file"
+                    curl -X POST -H "Content-Type: application/sparql-update" -d @"$query_file" \
+                      -k \
+                      -u '$(FUSEKI_USERNAME):$(FUSEKI_PASSWORD)' \
+                      -H "Host: $(FUSEKI_DOMAIN_NAME)" \
+                      https://localhost:8443/$(FUSEKI_DATASET)/update
+                    
+                    # Check if the query was successful
+                    if [ $? -ne 0 ]; then
+                      echo "##vso[task.logissue type=error]Failed to apply query: $query_file"
+                      exit 1
+                    fi
+                  done
+
+            - task: CmdLine@2
               displayName: "Upload vocabularies"
               inputs:
                 script: |
